GET http://localhost:5000/comment

###

POST  http://localhost:5000/comment/store
Content-Type: application/json

{
    "user": "6161bcdb5318e93abce45f24",
    "room": "61727b0fa3636ccdad9a787c",
    "content": "Hello ae safasf",
    "parentComment": "61c3ee18d244d8a137d57842"
}

###
GET  http://localhost:5000/user/load
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjYxNjFjMTIxMWNhYTQ2YWIxMTZmMjYyYiIsImlhdCI6MTYzNTY1MjUyN30.uTE2ScE17Va5DSSbgk2Zm4xRd0Bj0xWUIqvl_k8O1_Q

###

POST  http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

###


GET http://localhost:5000/booking
###

POST http://localhost:5000/room
Content-Type: application/json

{
   "search": 69
}

###

DELETE   http://localhost:5000/comment/61c3ee497f210152c3026441

###

POST  http://localhost:5000/typeRoom/store
Content-Type: application/json

{
    "name": "Single 3"
}


###

GET  http://localhost:5000/booking
###

PUT  http://192.168.1.128:5000/comment/61c48936bdb992e32dab503f
Content-Type: application/json

{
    "user": "6161bcdb5318e93abce45f24",
    "room": "61743af087a3ae875c1f1e86",
    "content": "Hello ae 123"
}