GET http://localhost:5000/message

###

POST  http://localhost:5000/conversation/store
Content-Type: application/json

{
    "userId": "61c08e80b1f5a80eb8e23155"
}

###
POST  http://localhost:5000/message/store
Content-Type: application/json

{
    "conversation": "61c89700c7688077c656004f",
    "user":"61c08e80b1f5a80eb8e23155",
    "content": "Hello anyone ?"
}

###
GET  http://localhost:5000/user/load
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjYxNjFjMTIxMWNhYTQ2YWIxMTZmMjYyYiIsImlhdCI6MTYzNTY1MjUyN30.uTE2ScE17Va5DSSbgk2Zm4xRd0Bj0xWUIqvl_k8O1_Q

###

POST  http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

###


GET http://localhost:5000/booking
###

POST http://localhost:5000/room
Content-Type: application/json

{
   "search": 69
}

###

DELETE   http://localhost:5000/comment/61c3ee497f210152c3026441

###

POST  http://localhost:5000/typeRoom/store
Content-Type: application/json

{
    "name": "Single 3"
}


###

GET  http://localhost:5000/booking
###

PUT  http://192.168.1.128:5000/comment/61c48936bdb992e32dab503f
Content-Type: application/json

{
    "user": "6161bcdb5318e93abce45f24",
    "room": "61743af087a3ae875c1f1e86",
    "content": "Hello ae 123"
}